/* weird bug where second exp of function is just not seen by parser.
TURNED OUT IT WAS JUST USING exp1 INSTEAD OF exp2 SOMEWHERE.
Still useful to check and make sure that the grammar can handle
functions with multiple exp in them */
let

function do_nothing1(a: int, b: string):int=
		(do_nothing2(a+1);9999;2;10;0)

function do_nothing2(d: int):string =
		(do_nothing1(d, "str");"hiding";" ";"hello")

in
	do_nothing1(0, "str2")
end
